language: perl
perl:
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

env: PERL_CPANM_OPT="--notest --force --skip-satisfied"

install:
    #- "cpanm Dist::Zilla::PluginBundle::BioPerl | tail -n 1"
    - "cpanm XML::Simple LWP::UserAgent | tail -n 1"
    - "cpanm Bio::Root::Root | tail -n 1"

script:
    - "prove -lr t"

notifications:
  email: false

# whitelist branches
branches:
  only:
    - master
