language: perl
perl:
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

env: PERL_CPANM_OPT="--notest --force --skip-satisfied"

install:
    - "cpanm Bio::Root::Root | tail -n 1"
    - "perl ./Build.PL --accept"

script:
    - "./Build test"

notifications:
  email: false

# whitelist branches
branches:
  only:
    - master
