language: perl
perl:
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

env: PERL_CPANM_OPT="--notest --force --skip-satisfied"

install:
    - "sudo apt-get install libdb-dev 2>&1 | tail -n 4"
    - "cpanm DB_File XML::Simple LWP::UserAgent | tail -n 1"
    - "cpanm Bio::Root::Root | tail -n 1"
    #Test coverage from Coveralls
    - cpanm --quiet --notest Devel::Cover::Report::Coveralls

script:
    #- "prove -lr t"
    - PERL5OPT=-MDevel::Cover=-coverage,all prove -lr t
    - cover -test -report coveralls

notifications:
  email: false

# whitelist branches
branches:
  only:
    - master
